# NumPy — Complete Theory Notes

> **NumPy = Numerical Python**
> A Python library used for numerical computing, arrays, mathematical operations, statistics, data preprocessing, and scientific computing.

| **NumPy Basics**                                                                                                                                                                                                           | **Array Basics**                                                                                                                                                                                                                                 |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| ### What is NumPy?<br><br>NumPy stands for **Numerical Python**. It is mainly used for working with numerical data and arrays.<br><br>`python<br>import numpy as np<br>`<br><br>`np` is the commonly used alias for NumPy. | ### NumPy Array<br><br>A NumPy array is a structured collection of values used for efficient numerical operations.<br><br>`python<br>arr = np.array([10, 20, 30, 40])<br>`<br><br>NumPy arrays are especially useful for numerical Data Science. |
| ### Why NumPy?<br><br>NumPy is useful for:<br>• Numerical calculations<br>• Mathematical operations<br>• Statistical analysis<br>• Matrix operations<br>• Data preprocessing<br>• Machine Learning preparation             | ### Python List vs NumPy Array<br><br>NumPy allows mathematical operations directly on arrays.<br><br>`python<br>arr * 2<br>`<br><br>Output:<br>`text<br>[20 40 60 80]<br>`                                                                      |
| ### Dimensions<br><br>Arrays can be:<br>• **1D** → sequence of values<br>• **2D** → rows and columns<br>• **3D** → collection of 2D arrays                                                                                 | ### Creating Arrays<br><br>`python<br>np.array([1, 2, 3])<br>`<br><br>For generating sequences:<br><br>`python<br>np.arange(1, 10)<br>`<br><br>`stop` value is excluded.                                                                         |
| ### Array Properties<br><br>`python<br>arr.ndim<br>arr.shape<br>arr.size<br>arr.dtype<br>`<br><br>• `ndim` → number of dimensions<br>• `shape` → structure<br>• `size` → total elements<br>• `dtype` → data type           | ### `np.arange()`<br><br>Syntax:<br><br>`python<br>np.arange(start, stop, step)<br>`<br><br>Example:<br>`python<br>np.arange(10, 51, 10)<br>`<br><br>Output:<br>`[10 20 30 40 50]`                                                               |
| ### 1D Array<br><br>`python<br>arr = np.array([10, 20, 30, 40])<br>`<br><br>`python<br>arr.ndim<br>`<br>Output: `1`                                                                                                        | ### 2D Array<br><br>`python<br>arr = np.array([<br>    [1, 2, 3],<br>    [4, 5, 6],<br>    [7, 8, 9]<br>])<br>`<br><br>Shape: `(3, 3)`                                                                                                           |
| ### 3D Array<br><br>`python<br>arr.reshape(2, 3, 4)<br>`<br><br>`(2, 3, 4)` means:<br>2 blocks × 3 rows × 4 columns                                                                                                        | ### Samples & Features<br><br>In a Data Science dataset:<br><br>**Rows → Samples / Observations**<br>**Columns → Features / Variables**                                                                                                          |
| ### Indexing<br><br>Indexing means accessing a particular element.<br><br>NumPy uses **zero-based indexing**.<br><br>`0 → first`<br>`1 → second`<br>`2 → third`                                                            | ### Negative Indexing<br><br>Negative indexes start from the end.<br><br>`-1 → last element`<br>`-2 → second-last`<br>`-3 → third-last`                                                                                                          |
| ### 2D Indexing<br><br>Syntax:<br><br>`python<br>arr[row, column]<br>`<br><br>Example:<br>`arr[1, 1]` selects the element at row 1 and column 1.                                                                           | ### Slicing<br><br>Syntax:<br><br>`python<br>arr[start:stop:step]<br>`<br><br>The `stop` index is excluded.                                                                                                                                      |
| ### Reverse Slicing<br><br>`python<br>arr[::-1]<br>`<br><br>Reverses the array because the step is `-1`.                                                                                                                   | ### 2D Slicing<br><br>`python<br>arr[row_start:row_stop,<br>    column_start:column_stop]<br>`<br><br>Example:<br>`python<br>arr[0:2, 1:3]<br>`                                                                                                  |
| ### Selecting Rows<br><br>`python<br>arr[0]<br>arr[0, :]<br>`<br><br>`:` means select everything in that dimension.                                                                                                        | ### Selecting Columns<br><br>`python<br>arr[:, 2]<br>`<br><br>`:` selects all rows and `2` selects column index 2.                                                                                                                               |
| ### Arithmetic Operations<br><br>NumPy performs operations element-wise.<br><br>`python<br>a + b<br>a - b<br>a * b<br>a / b<br>`                                                                                           | ### Scalar Operations<br><br>A scalar is a single value.<br><br>`python<br>arr * 2<br>arr + 100<br>`<br><br>The value is applied to every element.                                                                                               |
| ### Boolean Conditions<br><br>Comparisons produce Boolean arrays.<br><br>`python<br>arr > 25<br>`<br><br>Result contains `True` and `False`.                                                                               | ### Boolean Indexing<br><br>Used for condition-based filtering.<br><br>`python<br>arr[arr > 25]<br>`<br><br>Only values satisfying the condition are selected.                                                                                   |
| ### Multiple Conditions<br><br>Use:<br>`&` → AND<br>`\|` → OR<br>`~` → NOT<br><br>Example:<br>`python<br>(arr > 20) & (arr < 80)<br>`                                                                                      | ### Conditional Replacement<br><br>Values can be changed using a condition.<br><br>`python<br>arr[arr > 50] = 0<br>`<br><br>Useful for data cleaning and preprocessing.                                                                          |
| ### Fancy Indexing<br><br>Select specific positions using indexes.<br><br>`python<br>arr[[0, 2, 4]]<br>`<br><br>This selects elements at indexes 0, 2 and 4.                                                               | ### Indexing Methods<br><br>**Indexing** → one position<br>**Slicing** → continuous range<br>**Fancy Indexing** → specific positions<br>**Boolean Indexing** → condition-based selection                                                         |
| ### Aggregation<br><br>Aggregation summarizes data.<br><br>Important functions:<br>`np.sum()`<br>`np.mean()`<br>`np.min()`<br>`np.max()`<br>`np.std()`                                                                     | ### Maximum & Minimum<br><br>`python<br>np.max(arr)<br>np.min(arr)<br>`<br><br>`max` → maximum value<br>`min` → minimum value                                                                                                                    |
| ### `argmax()` & `argmin()`<br><br>`python<br>np.argmax(arr)<br>np.argmin(arr)<br>`<br><br>`argmax` → index of maximum value<br>`argmin` → index of minimum value                                                          | ### Mean<br><br>Mean is the average value.<br><br>\(Mean = \frac{Sum}{Number\ of\ values}\)<br><br>`python<br>np.mean(data)<br>`                                                                                                                 |
| ### Standard Deviation<br><br>Measures the spread or variation of data.<br><br>`python<br>np.std(data)<br>`<br><br>Small SD → values are closer together<br>Large SD → values are more spread out                          | ### `ddof`<br><br>Default:<br>`python<br>np.std(data)<br>`<br>`ddof = 0`<br><br>Sample standard deviation:<br>`python<br>np.std(data, ddof=1)<br>`                                                                                               |
| ### Axis<br><br>`axis` tells NumPy along which dimension an operation should be performed.<br><br>`axis=0` → column-wise result<br>`axis=1` → row-wise result                                                              | ### Axis Example<br><br>`python<br>np.sum(data, axis=0)<br>`<br>→ sum of each column<br><br>`python<br>np.sum(data, axis=1)<br>`<br>→ sum of each row                                                                                            |
| ### `keepdims=True`<br><br>Keeps the reduced dimension after aggregation.<br><br>`python<br>np.sum(arr, axis=1,<br>       keepdims=True)<br>`                                                                              | ### Why `keepdims`?<br><br>Useful when the result needs to work with the original array through **broadcasting**.                                                                                                                                |
| ### Reshape<br><br>Changes the shape/structure without changing the values.<br><br>`python<br>arr.reshape(3, 4)<br>`                                                                                                       | ### Reshape Rule<br><br>The number of elements must remain the same.<br><br>`12 elements → (3,4)` ✓<br>`12 elements → (2,6)` ✓<br>`12 elements → (3,5)` ✗                                                                                        |
| ### Flatten<br><br>Converts a multidimensional array into 1D.<br><br>`python<br>arr.flatten()<br>`                                                                                                                         | ### Transpose<br><br>Exchanges rows and columns.<br><br>`python<br>arr.T<br>`<br><br>`(2,3)` → `(3,2)`                                                                                                                                           |
| ### Broadcasting<br><br>Allows operations between compatible arrays or between an array and a scalar.<br><br>`python<br>arr + 100<br>`                                                                                     | ### Broadcasting Rule<br><br>Dimensions are compatible when:<br>• They are equal, or<br>• One dimension is `1`                                                                                                                                   |
| ### Row-Wise Normalization<br><br>`python<br>row_sum = np.sum(<br>    arr, axis=1,<br>    keepdims=True<br>)<br><br>result = arr / row_sum<br>`                                                                            | ### Feature-Wise Analysis<br><br>For feature-wise statistics:<br><br>`python<br>np.mean(data, axis=0)<br>np.min(data, axis=0)<br>np.max(data, axis=0)<br>np.std(data, axis=0)<br>`                                                               |
| ### Standardization<br><br>Uses mean and standard deviation.<br><br>Formula:<br>`python<br>(x - mean) / std<br>`<br><br>`z = 0` → value equals mean<br>`z > 0` → above mean<br>`z < 0` → below mean                        | ### Min-Max Normalization<br><br>Uses minimum and maximum values.<br><br>Formula:<br>`python<br>(x - min) / (max - min)<br>`<br><br>Usually transforms values to the range `0–1`.                                                                |
| ### Standardization vs Normalization<br><br>**Standardization** → Mean + Standard Deviation<br><br>**Min-Max** → Minimum + Maximum                                                                                         | ### Counting Conditions<br><br>`True → 1`<br>`False → 0`<br><br>Therefore:<br>`python<br>np.sum(data > 30)<br>`<br>can count how many values satisfy the condition.                                                                              |

---

# NumPy Quick Revision

| **Concept**       | **Syntax / Meaning**         |
| ----------------- | ---------------------------- |
| Import            | `import numpy as np`         |
| Create Array      | `np.array([1, 2, 3])`        |
| Create Sequence   | `np.arange(1, 10)`           |
| Dimensions        | `arr.ndim`                   |
| Shape             | `arr.shape`                  |
| Total Elements    | `arr.size`                   |
| Data Type         | `arr.dtype`                  |
| Indexing          | `arr[0]`                     |
| 2D Indexing       | `arr[row, column]`           |
| Slicing           | `arr[start:stop:step]`       |
| Reverse           | `arr[::-1]`                  |
| Boolean Filtering | `arr[arr > 50]`              |
| Fancy Indexing    | `arr[[0, 2, 4]]`             |
| Sum               | `np.sum(arr)`                |
| Mean              | `np.mean(arr)`               |
| Maximum           | `np.max(arr)`                |
| Minimum           | `np.min(arr)`                |
| Maximum Index     | `np.argmax(arr)`             |
| Minimum Index     | `np.argmin(arr)`             |
| Reshape           | `arr.reshape(rows, columns)` |
| Row-wise          | `axis=1`                     |
| Column-wise       | `axis=0`                     |
| Keep Dimension    | `keepdims=True`              |
| Standardization   | `(x - mean) / std`           |
| Min-Max           | `(x - min) / (max - min)`    |

## Important Rules

> **`ndim` → dimensions**
> **`shape` → structure**
> **`size` → total elements**
> **`dtype` → data type**
>
> **`axis=0` → column-wise result**
> **`axis=1` → row-wise result**
>
> **`max` → value**
> **`argmax` → index**
>
> **`min` → value**
> **`argmin` → index**
>
> **Boolean indexing → condition-based filtering**
> **Fancy indexing → specific indexes**
>
> **`reshape` → changes shape, not number of elements**
> **`keepdims=True` → keeps reduced dimension**
> **Broadcasting → allows compatible arrays to work together**


<h1 align="center">BASICS OF NUMPY
</h1>




In [ ]:
import numpy as np

Q1 Create a NumPy array from the Python list [10, 20, 30, 40, 50] and print the array.
 

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)

Q2 Create a NumPy array containing [10, 20, 30, 40, 50, 60]. Find and print its:
Number of dimensions
Shape
Size
Data type

In [ ]:
arr=np.array([10,20,30,40,50,60])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

Q3. Indexing and Slicing
Create the array [5, 10, 15, 20, 25, 30, 35] and:
Access the element 20.
Extract the first 3 elements.
Extract the last 3 elements.
Extract every second element.

In [ ]:
arr=np.array([5,10,15,20,25,30,35])
print(arr[3])
print(arr[:3])
print(arr[-3:])
print(arr[1:7:2])

Q4 Basic Array Operations
Create two NumPy arrays:
a = [10, 20, 30]
b = [2, 4, 5]
Perform:
Addition
Subtraction
Multiplication
Division

In [ ]:
arr=np.array([10,20,30])
arr_2=np.array([2,4,5])
print("ADD",arr+arr_2)
print("subtract",arr-arr_2)
print("multiply",arr*arr_2)
print("divide",arr/arr_2)

Q5 2D Array

Create the following 2D NumPy array:<br>
1 2 3<br>
4 5 6<br>
7 8 9<br><br>

Then:<br>
- Access the element 5<br>
- Extract the first row<br>
- Extract the last column<br>
- Find the shape of the array

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])
print(arr[0,:])
print(arr[:,2])
print(arr.shape)


<h1 align="center">INTERMEDIATE
</h1>




Q6 Array Creation<BR>
Create a NumPy array containing numbers from 1 to 20 without manually typing all the numbers.

In [ ]:
arr=np.arange(0,21) #arange(array range) use to create array of no. in sequence
print(arr)

Q7 Even Numbers<br>
From the array 1–50, extract only the even numbers.

In [ ]:
arr=np.arange(1,51)
even_no=[]
for i in arr:
    if i%2==0:
         even_no.append(i)
print(np.array(even_no) ) 


#METHOD 2 NUMPY BOOLEAN INDEXING 
arr=np.arange(1,51)
even_no =arr%2==0
print(even_no)  

#METHOD 3
arr=np.arange(1,51)
even_no=arr[arr%2==0]
print(even_no)
   

Q8 Create an array containing numbers from 1–12 and reshape it into:<br>
1   2   3   4<br>
5   6   7   8<br>
9  10  11  12<br>

In [ ]:
arr=np.arange(1,13)
print(arr)
arr2=arr.reshape(3,4) #(rows,colunmn)
print(arr2)

Q9 Create an array containing 1–24 and reshape it into a 3D array of shape (2, 3, 4).<br>
Check its:
ndim,
shape,
size,

In [ ]:
arr=np.arange(1,25)
arr2=arr.reshape(2,3,4) #2 blocks, 3 rows ,4 column
print(arr2)
print("NO. OF DIMENSION",arr2.ndim)
print("SHAPE",arr2.shape)
print("SIZE",arr2.size)

Q10 Given:<br>
arr = np.array([<BR>
    [10, 20, 30, 40],<br>
    [50, 60, 70, 80],<br>
    [90, 100, 110, 120]<br>
])<br>
Find:
70,
100,
First row,
Last row,
Second column,
<br>
Using the same array, extract:<BR>
20  30 <br>
60  70<br>
 
Using the same array, extract only the last column.
Expected:
[40 80 120]

In [ ]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[1,2])
print(arr[2,1])
print("FIRST ROW",arr[0,])
print("SECOND ROW",arr[2,])
print("LAST ROW",arr[1,])

print(arr[0:2,1:3])

print(arr[:,3])

Q11 Reverse an Array
Given:
arr = np.array([10, 20, 30, 40, 50])
Reverse the array using NumPy slicing.<BR>
Expected:
[50 40 30 20 10]

In [ ]:
arr=np.arange(10,51,10) #STAER,STOP,STEP
print(arr)
rev_arr=arr[::-1] #SLICING FORMAT(START,STOP,STEP)
print(rev_arr)

Q12 Boolean Masking<BR>
Given:<BR>
arr = np.array([12, 45, 7, 89, 23, 56, 3, 78])<BR>
Extract all values greater than 50.<br>
Using the same array, extract values that are:
greater than 20 AND less than 80.

In [ ]:
arr=np.array([12,45,89,23,56,3,78])
print(arr)
arr2=[]
for i in arr:
    if i >50:
        arr2.append(i)
print(arr2)    

for i in arr:
    if 20<i<80:
        arr2.append(i)
print(arr2)    
    

Q13 Replace Values
Given:<BR>
arr = np.array([10, 25, 60, 15, 80, 5, 90])
Replace every value greater than 50 with 0.

In [ ]:
arr = np.array([10, 25, 60, 15, 80, 5, 90])
arr[arr > 50] = 0
print(arr)

Q14 Sum by Axis
Given:
arr = np.array([ <br>
    [10, 20, 30],<br>
    [40, 50, 60],<br>
    [70, 80, 90]<br>
])<br>
Find:<br>
Total sum,
Sum of each row,
Sum of each column<BR>
Using the same array, find:<BR>
Mean,
Maximum,
Minimum,
Index of maximum value,
Index of minimum value.

In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])

print("SUM",np.sum(arr))
print("SUM OF EACH ROW ",np.sum(arr,axis=1))
print("SUM OF EACH COLUMN ",np.sum(arr,axis=0))

print("MEAN",np.mean(arr))
print("MAXIMUM",np.max(arr))
print("MINIMUM",np.min(arr))
print("INDEX OF MAXIMUM VALUE",np.argmax(arr))
print("INDEX OF MINIMUM VALUE",np.argmin(arr))

Q15 Axis Practice<br>
Given:
arr = np.array([<br>
    [1, 2, 3],<br>
    [4, 5, 6]<br>
])<br>
Find the result of:
arr.sum(axis=0),
arr.sum(axis=1)<br>
Then explain what axis 0 and axis 1 mean.

In [ ]:
#SUM OF COLUMN [5,7,9]
#SUM OF ROW [6,15]
#axis 0 means colum wise and axis 1 means row wise


Q16 Broadcasting
Given:<br>
arr = np.array([ <br>
    [10, 20, 30],<br>
    [40, 50, 60],<br>
    [70, 80, 90]<br>
])<br>

bonus = np.array([1, 2, 3])
Add bonus to every row.<br>
Expected:<br>
11 22 33<br>
41 52 63<br>
71 82 93<br>


In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
bonous=np.array([1,2,3])
arr2=arr+bonous
print(arr2)

Q17 Broadcasting with Scalar<br>
Given:<br>
arr = np.array([<br>
    [10, 20, 30],<br>
    [40, 50, 60]<br>
])<br>
Add 100 to every element.
Then multiply every element by 2.

In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
arr=(arr+100)*2
print(arr)

Q18 Row-wise Normalization
Given:<BR>
arr = np.array([<BR>
    [10, 20, 30],<BR>
    [20, 40, 60]<BR>
])<BR>
Divide each row by its row sum.<BR>
Hint: Think about axis and broadcasting.<BR>

In [ ]:
arr=np.array([[10,20,30],[20,40,60]])
row_sum=np.sum(arr,axis=1,keepdims=True) #WE US EKEEPDIMS=TRUE BECZ ARRAY IS 2D AND SUM OF ROW IS IN 1D TO MAKE IT 2D FOR DIVISON WE USE KEEPDIMS=TRUE

result=arr/row_sum
print(row_sum)
print(result)

Q19 Fancy Indexing
Given:<BR>
arr = np.array([10, 20, 30, 40, 50, 60])<BR>
Extract elements at indexes:
0, 2, 4<BR>
Expected:<BR>
[10 30 50]

In [ ]:
arr=np.arange(10,61,10)
print(arr)

print(arr[[0,2,4]]) #this is fancy indexing

Q20 2D Fancy Indexing <br>
Given:<br>
arr = np.array([<br>
    [10, 20, 30],<br>
    [40, 50, 60],<br>
    [70, 80, 90]<br>
])<br>
Extract:<br>
10, 50, 90<br>
using indexing.

In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr,"\n")
print(arr[[0,1,2],[0,1,2]]) #arr[[row_indexes], [column_indexes]]


<h2 style="text-align: center; color: yellow;">Data Science-Oriented NumPy</h2>

<p style="text-align: center;">
These are especially important because they start feeling like actual data science.
</p>

<h3>Q21 Student Marks</h3>

<b>Given:</b>

<table>
<tr>
<th>Student</th>
<th>Subject 1</th>
<th>Subject 2</th>
<th>Subject 3</th>
</tr>

<tr>
<td>Student 1</td>
<td>78</td>
<td>85</td>
<td>90</td>
</tr>

<tr>
<td>Student 2</td>
<td>65</td>
<td>70</td>
<td>72</td>
</tr>

<tr>
<td>Student 3</td>
<td>92</td>
<td>88</td>
<td>95</td>
</tr>

<tr>
<td>Student 4</td>
<td>55</td>
<td>60</td>
<td>58</td>
</tr>
</table>

<br>

Each row represents a student and each column represents a subject.

<b>Find:</b>

1. Average marks of each student
2. Average marks of each subject
3. Highest mark
4. Student with the highest average
5. Students whose average is greater than 75

In [89]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [92, 88, 95],
    [55, 60, 58]
])

# 1. Average marks of each student
student_avg = np.mean(marks, axis=1)
print("Average marks of each student:", student_avg)

# 2. Average marks of each subject
subject_avg = np.mean(marks, axis=0)
print("Average marks of each subject:", subject_avg)

# 3. Highest mark
highest_mark = np.max(marks)
print("Highest mark:", highest_mark)

# 4. Student with the highest average
highest_avg = np.max(student_avg)
highest_avg_student = np.argmax(student_avg) + 1
print("Highest average:", highest_avg)
print("Student with the highest average: Student", highest_avg_student)

# 5. Students whose average is greater than 75
students_above_75 = np.where(student_avg > 75)[0] + 1
print("Students whose average is greater than 75:", students_above_75)

Average marks of each student: [84.33333333 69.         91.66666667 57.66666667]
Average marks of each subject: [72.5  75.75 78.75]
Highest mark: 95
Highest average: 91.66666666666667
Student with the highest average: Student 3
Students whose average is greater than 75: [1 3]


Q22 Temperature Data
Given:<BR>
temperature = np.array([32, 35, 31, 29, 40, 38, 36])<BR>
Find:<BR>
Average temperature<BR>
Maximum temperature<BR>
Minimum temperature<BR>
Days where temperature was above 35<BR>
Number of days above 35<BR>

In [96]:
temperature = np.array([32, 35, 31, 29, 40, 38, 36])

avg_temp=np.mean(temperature)
min_temp=np.min(temperature)
max_temp=np.max(temperature)
temp_above_35=temperature[temperature>35]
day_above_35=np.sum(temperature>35)

print("AVG TEMP=",avg_temp)
print("MIN TEMP=",min_temp)
print("MAX TEMP=",max_temp)
print("TEMP ABOVE 35=",temp_above_35)
print("Number of days above 35:", day_above_35)

AVG TEMP= 34.42857142857143
MIN TEMP= 29
MAX TEMP= 40
TEMP ABOVE 35= [40 38 36]
Number of days above 35: 3


Q23. Sales Data


Analyze the following monthly sales data using NumPy.


Given:

| Month | Product 1 | Product 2 | Product 3 |
|:-----:|----------:|----------:|----------:|
| Month 1 | 100 | 200 | 150 |
| Month 2 | 300 | 250 | 400 |
| Month 3 | 200 | 180 | 220 |

 Find:

1. **Total sales**
2. **Total sales for each month**
3. **Total sales for each product**
4. **Month with the highest sales**
5. **Product with the highest total sales**

**Note:**
- Rows represent **months**.
- Columns represent **products**.
- Use NumPy functions such as `np.sum()`, `np.argmax()`, and array operations wherever appropriate.

In [109]:
sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [200, 180, 220]
])
total_sales=np.sum(sales)
total_sale_each_month=np.sum(sales,axis=1)
total_sale_each_product=np.sum(sales,axis=0)

month_sale=np.sum(sales,axis=1)
month_wise_highest_sale=np.argmax(month_sale)+1

product_sale=np.sum(sales,axis=0)
product_wise_highest_sale=np.argmax(product_sale)+1




print("Total sales =",total_sales)
print("Total sales for each month =",total_sale_each_month)
print("Total sales for each product =",total_sale_each_product)
print("Month with the highest sales = Month",month_wise_highest_sale)
print("Product with the highest total sales = product",product_wise_highest_sale)

Total sales = 2000
Total sales for each month = [450 950 600]
Total sales for each product = [600 630 770]
Month with the highest sales = Month 2
Product with the highest total sales = product 3


Q24 Standardization ⭐<BR>
Given:<BR>
data = np.array([10, 20, 30, 40, 50])<BR>
Calculate the standardized values using:<BR>
z = (x - mean) / standard_deviation<BR>
Do this using NumPy functions.
This is directly connected to Machine Learning preprocessing.

In [111]:
data = np.array([10, 20, 30, 40, 50])

mean=np.mean(data)
std_dev=np.std(data)

z=(data-mean)/std_dev

print("MEAN =",mean)
print("STANDARD DEVIATION =",std_dev)
print("STANDARDIZED VALUE =",z)

MEAN = 30.0
STANDARD DEVIATION = 14.142135623730951
STANDARDIZED VALUE = [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


 🔥 Q25 | Mini Data Science Challenge

 📌 Given Dataset

| Feature 1 | Feature 2 | Feature 3 |
|:---------:|:---------:|:---------:|
| 10 | 20 | 30 |
| 15 | 25 | 35 |
| 20 | 30 | 40 |
| 25 | 35 | 45 |
| 30 | 40 | 50 |

 📝 Dataset Representation

```python
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45],
    [30, 40, 50]
])
Treat each row as a data sample and each column as a feature.
Find:
Number of samples
Number of features
Mean of each feature
Maximum of each feature
Minimum of each feature
Standard deviation of each feature
Samples where the second feature > 30
Normalize each feature using min-max normalization
normalized = (x - min) / (max - min)

In [123]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45],
    [30, 40, 50]
])

print("Number of samples",data.shape[0])
print("Number of feature",data.shape[1])
print("Mean of each feature =", np.mean(data, axis=0))
print("Minimum of  each feature",np.min(data ,axis=0))
print("Maxium of  each feature",np.max(data ,axis=0))
print("Standard Devation of each feature",np.std(data ,axis=0))
print("Samples where second feature > 30 =" ,data[data[:, 1] > 30])

min=np.min(data,axis=0)
max=np.max(data ,axis=0)
nor=(data-min)/(max-min)

print("Normalized value", nor)

Number of samples 5
Number of feature 3
Mean of each feature = [20. 30. 40.]
Minimum of  each feature [10 20 30]
Maxium of  each feature [30 40 50]
Standard Devation of each feature [7.07106781 7.07106781 7.07106781]
Samples where second feature > 30 = [[25 35 45]
 [30 40 50]]
Normalized value [[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]
