<h1 align="center">BASICS OF NUMPY
</h1>




In [1]:
import numpy as np

Q1 Create a NumPy array from the Python list [10, 20, 30, 40, 50] and print the array.
 

In [2]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


Q2 Create a NumPy array containing [10, 20, 30, 40, 50, 60]. Find and print its:
Number of dimensions
Shape
Size
Data type

In [3]:
arr=np.array([10,20,30,40,50,60])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(6,)
6
int32


Q3. Indexing and Slicing
Create the array [5, 10, 15, 20, 25, 30, 35] and:
Access the element 20.
Extract the first 3 elements.
Extract the last 3 elements.
Extract every second element.

In [4]:
arr=np.array([5,10,15,20,25,30,35])
print(arr[3])
print(arr[:3])
print(arr[-3:])
print(arr[1:7:2])

20
[ 5 10 15]
[25 30 35]
[10 20 30]


Q4 Basic Array Operations
Create two NumPy arrays:
a = [10, 20, 30]
b = [2, 4, 5]
Perform:
Addition
Subtraction
Multiplication
Division

In [5]:
arr=np.array([10,20,30])
arr_2=np.array([2,4,5])
print("ADD",arr+arr_2)
print("subtract",arr-arr_2)
print("multiply",arr*arr_2)
print("divide",arr/arr_2)

ADD [12 24 35]
subtract [ 8 16 25]
multiply [ 20  80 150]
divide [5. 5. 6.]


Q5 2D Array

Create the following 2D NumPy array:<br>
1 2 3<br>
4 5 6<br>
7 8 9<br><br>

Then:<br>
- Access the element 5<br>
- Extract the first row<br>
- Extract the last column<br>
- Find the shape of the array

In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])
print(arr[0,:])
print(arr[:,2])
print(arr.shape)


5
[1 2 3]
[3 6 9]
(3, 3)


<h1 align="center">INTERMEDIATE
</h1>




Q6 Array Creation<BR>
Create a NumPy array containing numbers from 1 to 20 without manually typing all the numbers.

In [7]:
arr=np.arange(0,21) #arange(array range) use to create array of no. in sequence
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q7 Even Numbers<br>
From the array 1–50, extract only the even numbers.

In [8]:
arr=np.arange(1,51)
even_no=[]
for i in arr:
    if i%2==0:
         even_no.append(i)
print(np.array(even_no) ) 


#METHOD 2 NUMPY BOOLEAN INDEXING 
arr=np.arange(1,51)
even_no =arr%2==0
print(even_no)  

#METHOD 3
arr=np.arange(1,51)
even_no=arr[arr%2==0]
print(even_no)
   

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Q8 Create an array containing numbers from 1–12 and reshape it into:<br>
1   2   3   4<br>
5   6   7   8<br>
9  10  11  12<br>

In [9]:
arr=np.arange(1,13)
print(arr)
arr2=arr.reshape(3,4) #(rows,colunmn)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Q9 Create an array containing 1–24 and reshape it into a 3D array of shape (2, 3, 4).<br>
Check its:
ndim,
shape,
size,

In [10]:
arr=np.arange(1,25)
arr2=arr.reshape(2,3,4) #2 blocks, 3 rows ,4 column
print(arr2)
print("NO. OF DIMENSION",arr2.ndim)
print("SHAPE",arr2.shape)
print("SIZE",arr2.size)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
NO. OF DIMENSION 3
SHAPE (2, 3, 4)
SIZE 24


Q10 Given:<br>
arr = np.array([<BR>
    [10, 20, 30, 40],<br>
    [50, 60, 70, 80],<br>
    [90, 100, 110, 120]<br>
])<br>
Find:
70,
100,
First row,
Last row,
Second column,
<br>
Using the same array, extract:<BR>
20  30 <br>
60  70<br>
 
Using the same array, extract only the last column.
Expected:
[40 80 120]

In [11]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[1,2])
print(arr[2,1])
print("FIRST ROW",arr[0,])
print("SECOND ROW",arr[2,])
print("LAST ROW",arr[1,])

print(arr[0:2,1:3])

print(arr[:,3])

70
100
FIRST ROW [10 20 30 40]
SECOND ROW [ 90 100 110 120]
LAST ROW [50 60 70 80]
[[20 30]
 [60 70]]
[ 40  80 120]


Q11 Reverse an Array
Given:
arr = np.array([10, 20, 30, 40, 50])
Reverse the array using NumPy slicing.<BR>
Expected:
[50 40 30 20 10]

In [12]:
arr=np.arange(10,51,10) #STAER,STOP,STEP
print(arr)
rev_arr=arr[::-1] #SLICING FORMAT(START,STOP,STEP)
print(rev_arr)

[10 20 30 40 50]
[50 40 30 20 10]


Q12 Boolean Masking<BR>
Given:<BR>
arr = np.array([12, 45, 7, 89, 23, 56, 3, 78])<BR>
Extract all values greater than 50.<br>
Using the same array, extract values that are:
greater than 20 AND less than 80.

In [13]:
arr=np.array([12,45,89,23,56,3,78])
print(arr)
arr2=[]
for i in arr:
    if i >50:
        arr2.append(i)
print(arr2)    

for i in arr:
    if 20<i<80:
        arr2.append(i)
print(arr2)    
    

[12 45 89 23 56  3 78]
[89, 56, 78]
[89, 56, 78, 45, 23, 56, 78]


Q13 Replace Values
Given:<BR>
arr = np.array([10, 25, 60, 15, 80, 5, 90])
Replace every value greater than 50 with 0.

In [ ]:
arr = np.array([10, 25, 60, 15, 80, 5, 90])
arr[arr > 50] = 0
print(arr)

[10 25  0 15  0  5  0]
